repos:
  - repo: local
    hooks:
      - id: actionlint
        name: actionlint
        entry: actionlint
        language: system
        files: ^\.github/workflows/.*\.ya?ml$
      - id: shellcheck
        name: shellcheck
        entry: shellcheck
        language: system
        files: ^unpack\.sh$
      - id: markdownlint
        name: markdownlint
        entry: markdownlint --config .markdownlint.json
        language: system
        files: ^(README\.md|CONTRIBUTING\.md|docs/getting_started\.md)$
