"""validate_datacard.py — validate a Genesis Mission Datacard v1.2 file against the upstream Pydantic model.

The Pydantic model in `scripts/genesis_models.py` is auto-generated by upstream from
the LinkML source and is the single source of truth for shape, types, enums,
and required fields. This module:

1. Loads the .md datacard, splits frontmatter from body, parses YAML.
2. Validates against the root Pydantic model via `GenesisDatacardClass.model_validate(data)`.
3. Converts Pydantic v2 ValidationError entries to structured Finding objects.
4. Runs a small set of *extras* (filename rule, workflow↔release alignment warning)
   that the schema doesn't express.
5. Emits structured findings via JSON (--json) or human-readable text.

To re-sync with upstream, re-vendor `scripts/genesis_models.py` and
`references/genesis_v1.0_template.md` from the same upstream commit.
"""

from __future__ import annotations
import argparse, json, re, sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

# Make the vendored Pydantic module importable when this script is invoked directly.
sys.path.insert(0, str(Path(__file__).resolve().parent))
import genesis_models  # noqa: E402

from pydantic import ValidationError  # noqa: E402


SKILL_ROOT = Path(__file__).resolve().parent.parent
RootModel = genesis_models.GenesisDatacardClass


# ---------- Data classes ----------

@dataclass
class Finding:
    code: str            # MISSING_REQUIRED | BAD_ENUM | BAD_FORMAT | INCONSISTENT | SCHEMA_VIOLATION
    field: str           # dotted path of the offending field
    severity: str = "error"   # error | warn | info
    message: str = ""

    def as_dict(self) -> dict:
        return {"code": self.code, "field": self.field,
                "severity": self.severity, "message": self.message}


@dataclass
class Result:
    findings: list[Finding] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not any(f.severity == "error" for f in self.findings)

    def as_dict(self) -> dict:
        return {"ok": self.ok, "findings": [f.as_dict() for f in self.findings]}


# ---------- Loading ----------

def load_datacard(path: Path) -> dict:
    """Load YAML frontmatter from a .md datacard."""
    text = Path(path).read_text(encoding="utf-8")
    parts = re.split(r"^---\s*$", text, maxsplit=2, flags=re.MULTILINE)
    if len(parts) < 2:
        raise ValueError(f"{path}: file does not have YAML frontmatter delimited by `---` lines")
    data = yaml.safe_load(parts[1])
    if not isinstance(data, dict):
        raise ValueError(f"{path}: frontmatter is not a YAML mapping")
    return data


# ---------- Pydantic validation ----------

def _pointer(loc: tuple) -> str:
    """Convert Pydantic's `loc` tuple to a dotted field path (e.g. `discoverability.authors[0].person`)."""
    parts = []
    for p in loc:
        if isinstance(p, int):
            parts.append(f"[{p}]")
        else:
            if parts:
                parts.append(f".{p}")
            else:
                parts.append(str(p))
    return "".join(parts) or "(root)"


def _code_for(err_type: str) -> str:
    """Map Pydantic v2 error types to our Finding codes."""
    if err_type == "missing":
        return "MISSING_REQUIRED"
    if err_type.startswith("enum") or err_type == "literal_error":
        return "BAD_ENUM"
    if err_type in ("string_pattern_mismatch", "url_parsing", "url_type", "date_parsing"):
        return "BAD_FORMAT"
    if err_type == "extra_forbidden":
        return "SCHEMA_VIOLATION"
    if err_type in ("union_tag_invalid", "union_tag_not_found"):
        return "INCONSISTENT"
    return "SCHEMA_VIOLATION"


def check_schema(data: dict) -> list[Finding]:
    """Validate data against the root Pydantic model; convert ValidationError to Findings."""
    findings: list[Finding] = []
    try:
        RootModel.model_validate(data)
    except ValidationError as e:
        for err in e.errors():
            findings.append(Finding(
                code=_code_for(err.get("type", "")),
                field=_pointer(err.get("loc", ())),
                severity="error",
                message=err.get("msg", "validation error"),
            ))
    return findings


# ---------- Extras (warn-level checks not in the schema) ----------

def get_field(data: dict, path: str) -> Any:
    MISSING = object()
    cur: Any = data
    for part in path.split("."):
        if isinstance(cur, dict) and part in cur:
            cur = cur[part]
        else:
            return MISSING
    return cur


def _snake_case(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", s.lower()).strip("_")


def check_extras(data: dict) -> list[Finding]:
    """Warn-level rules: filename match + workflow/release alignment."""
    out: list[Finding] = []

    # 1. Filename rule.
    name_paths = ("discoverability.identification.name", "identification.name")
    filename_paths = ("discoverability.datacard.filename", "datacard.filename")
    name = next((v for p in name_paths for v in [get_field(data, p)] if isinstance(v, str)), None)
    filename = next((v for p in filename_paths for v in [get_field(data, p)] if isinstance(v, str)), None)
    if name and filename:
        expected = f"genesis_datacard_{_snake_case(name)}.md"
        if filename != expected:
            out.append(Finding(
                code="INCONSISTENT",
                field="datacard.filename",
                severity="warn",
                message=f"expected `{expected}` from name=`{name}`; got `{filename}`",
            ))

    # 2. workflow.state ↔ release_status alignment (warn).
    alignment = {
        "Raw": ["Draft"], "Processing": ["Draft"], "QA": ["Draft"], "Analysis": ["Draft"],
        "Review": ["Under_Review"],
        "Embargo": ["Approved", "Published"],
        "Published": ["Approved", "Published"],
        "Archived": ["Deprecated", "Published"],
    }
    state = next((v for p in ("discoverability.workflow.state", "workflow.state")
                  for v in [get_field(data, p)] if isinstance(v, str)), None)
    status = next((v for p in ("discoverability.release_status", "release_status")
                   for v in [get_field(data, p)] if isinstance(v, str)), None)
    if state in alignment and status:
        allowed = alignment[state]
        if status not in allowed:
            out.append(Finding(
                code="INCONSISTENT",
                field="workflow.state",
                severity="warn",
                message=(f"workflow.state=`{state}` typically aligns with "
                         f"release_status in {allowed}; got `{status}`"),
            ))

    return out


# ---------- Orchestrator ----------

def validate(data: dict) -> Result:
    findings: list[Finding] = []
    findings.extend(check_schema(data))
    findings.extend(check_extras(data))
    return Result(findings=findings)


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Validate a Genesis Mission Datacard v1.2 file.")
    p.add_argument("file", type=Path, help="Path to datacard .md file")
    p.add_argument("--profile",
                   help="Legacy compatibility flag — ignored. Profiles were replaced by supports_* capability flags.")
    p.add_argument("--json", dest="emit_json", action="store_true",
                   help="Emit machine-readable JSON")
    args = p.parse_args(argv)

    if args.profile:
        sys.stderr.write("[warn] --profile is ignored (profiles replaced by supports_* flags in v2).\n")

    data = load_datacard(args.file)
    result = validate(data)

    if args.emit_json:
        print(json.dumps(result.as_dict(), indent=2))
    else:
        if result.ok:
            print(f"OK: {args.file} valid against Genesis Datacard v1.2 schema")
        else:
            n_errors = sum(1 for f in result.findings if f.severity == "error")
            print(f"FAIL: {args.file} ({n_errors} schema errors)")
        for f in result.findings:
            print(f"  [{f.severity}] {f.code} {f.field}: {f.message}")
    return 0 if result.ok else 1


if __name__ == "__main__":
    sys.exit(main())
